#!/usr/bin/env python
# -*- coding:utf8 -*-
#from django.contrib.auth.models import User
"""
Django settings for video_omsa project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SERVER_DOMAIN = "localhost"
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '#_7im+_2o+@)gt+h9ve2q0u8-2c0wde=hh5y8m&&b^c=a5r!n$'
TIME_ZONE = 'Asia/Shanghai'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
# auth system
AUTHENTICATION_BACKENDS = (
	'django.contrib.auth.backends.ModelBackend', #django default auth system
	'guardian.backends.ObjectPermissionBackend',
)
#ANONYMOUS_USER_ID=-1

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'video',
    'aliyun',
    'zabbix',
   # 'verifycode',
    'captcha',
    'django_celery_results',
# xadmin 项目配置
#    'xadmin',
#    'crispy_forms',
#    'reversion',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
# 调试工具
#    'debug_toolbar.middleware.DebugToolbarMiddleware',
)

ROOT_URLCONF = 'video_omsa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'video_omsa.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'django_video',
	'USER': 'root',
	'PASSWORD':'yjy_video@123',
	'HOST':'localhost',
	'PORT':'3306',
    },
    'xiyizhiyeyishi': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'yjy_xiyizhiyeyishi',
	'USER': 'root',
	'PASSWORD':'yjy_video@123',
	'HOST':'localhost',
	'PORT':'3306',
    },
    'tcmsq': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'tcmsq',
	'USER': 'root',
	'PASSWORD':'yjy_video@123',
	'HOST':'localhost',
	'PORT':'3306',
    },
    'yjy_xiyizonghe': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'yjy_xiyizonghe',
	'USER': 'root',
	'PASSWORD':'yjy_video@123',
	'HOST':'localhost',
	'PORT':'3306',
    },
    'zhongyizonghe': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'yjy_zhongyizonghe',
	'USER': 'root',
	'PASSWORD':'yjy_video@123',
	'HOST':'localhost',
	'PORT':'3306',
    },
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

USE_I18N = True

USE_L10N = True
AUTH_USER_MODEL = 'auth.User'
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_ROOT = '/www/web/django_video/video_omsa/static/'
STATIC_URL = '/static/'
STAICFILES_DIRS= ( 
         os.path.join(BASE_DIR + '/common_static/'),
)
#############
# debug配置 # 
#############
INTERNAL_IPS=('127.0.0.1',)
## 日志
LOGGING = {  
    'disable_existing_loggers': False,  
    'version': 1,  
    'handlers': {  
        'console': {  
            # logging handler that outputs log messages to terminal  
            'class': 'logging.StreamHandler',  
            'level': 'DEBUG', # message level to be written to console  
        },  
    },  
    'loggers': {  
        '': {  
            # this sets root level logger to log debug and higher level  
            # logs to console. All other loggers inherit settings from  
            # root level logger.  
            'handlers': ['console'],  
            'level': 'DEBUG',  
            'propagate': False, # this tells logger to send logging message  
                                # to its parent (will send if set to True)  
        },  
        'django.db': {  
            # django also has database level logging  
        },  
    },  
}

# django_simple_captcha 验证码配置   
# 格式  
CAPTCHA_OUTPUT_FORMAT = u'%(text_field)s %(hidden_field)s %(image)s'  
# 噪点样式  
CAPTCHA_NOISE_FUNCTIONS = ('captcha.helpers.noise_null', # 没有样式  
    'captcha.helpers.noise_arcs', # 线
    # 'captcha.helpers.noise_dots', # 点  
)  
# 图片大小  
CAPTCHA_IMAGE_SIZE = (200, 25)
CAPTCHA_BACKGROUND_COLOR = '#ffffff'  
CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.random_char_challenge' # 图片中的文字为随机英文字母，如 mdsh  
# CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.math_challenge'    # 图片中的文字为数字表达式，如1+2=</span>  
  
CAPTCHA_LENGTH = 5 # 字符个数
CAPTCHA_TIMEOUT = 1 # 超时(minutes)  

# redis 缓存配置
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://:yjy_video@123@127.0.0.1:18669/2",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}
REDIS_TIMEOUT=7*24*60*60
CUBES_REDIS_TIMEOUT=60*60
NEVER_REDIS_TIMEOUT=365*24*60*60

#### 全局配置文件 #####
## mp4 服务器视频上传资源位置
MP4_SERVER_DIR = "/data/original/"
MP4_UPLOAD_DIR = "/data/original/new/"

## celery 配置项 ###
# Celery settings
#: Only add pickle to this list if your broker is secured
#: from unwanted access (see userguide/security.html)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_RESULT_BACKEND = 'django-db'
CELERY_TASK_SERIALIZER = 'json'
CELERY_BROKER_URL = 'redis://:yjy_video@123@127.0.0.1:18669/5'

# 上线和预上线的ip
PREPARE_SERVER_IP = '10.26.160.177'
ONLINE_SERVER_IP = '10.24.203.239'

# 各学科商品的goods_service_id
APP_GOOD_SERVICE_IDS = {
        'yjy_xiyizonghe':{
            'goods_id':{
                '1':99, #  直播课
                '2':99, #  基础课
                '3':99, #  强化课
                '4':99, #  冲刺课
                '5':99  #  专题课
            },
            'service_id':{
                '1':99, #  直播课
                '2':99, #  基础课
                '3':99, #  强化课
                '4':99, #  冲刺课
                '5':99  #  专题课
            }
        },
        'yjy_xiyizhiyeyishi':{
            'goods_id':{
                '2':113, # 基础
                '3':115, # 技能
                '4':114, # 冲刺
            },
            'service_id':{
                '2':113, # 基础
                '3':115, # 技能
                '4':114, # 冲刺
            }
        },
        'tcmsq':{
            'goods_id':{
                '2':144, # 精讲
                '3':142, # 技能
                '4':145  # 冲刺
            },
            'service_id':{
                '2':144, # 精讲
                '3':142, # 技能
                '4':145  # 冲刺
            }
        },
        'yjy_zhongyizonghe':{
            'goods_id':{
                '2':136, # 精讲
                '3':136, # 冲刺
                '4':136  # 技能
            },
            'service_id':{
                '2':136, # 精讲
                '3':136, # 冲刺
                '4':136  # 技能
            }
        }
    }

# 邮件配置
EMAIL_HOST = "smtp.163.com"
EMAIL_PORT = 465
EMAIL_HOST_USER = "shixiaobo8@163.com"
EMAIL_HOST_PASSWORD = 'My163code89'
EMAIL_FROM = "shixiaobo8@163.com"
# EMAIL_BACKEND = 'django_smtp_ssl.SSLEmailBackend'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  #email后端
EMAIL_USE_TLS = False   #是否使用TLS安全传输协议
EMAIL_USE_SSL = True    #是否使用SSL加密，qq企业邮箱要求使用
