#!/usr/bin/env python
# -*- coding:utf8 -*-
#from django.contrib.auth.models import User
"""
Django settings for video_omsa project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '#_7im+_2o+@)gt+h9ve2q0u8-2c0wde=hh5y8m&&b^c=a5r!n$'
TIME_ZONE = 'Asia/Shanghai'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']
# auth system
AUTHENTICATION_BACKENDS = (
	'django.contrib.auth.backends.ModelBackend', #django default auth system
	'guardian.backends.ObjectPermissionBackend',
)
#ANONYMOUS_USER_ID=-1

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'video',
    'aliyun',
    'zabbix',
   # 'verifycode',
    'captcha',
# xadmin 项目配置
#    'xadmin',
#    'crispy_forms',
#    'reversion',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
# 调试工具
#    'debug_toolbar.middleware.DebugToolbarMiddleware',
)

ROOT_URLCONF = 'video_omsa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'video_omsa.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'django_video',
	'USER': 'root',
	'PASSWORD':'123456',
	'HOST':'localhost',
	'PORT':'3306',
    },
    'xiyizhiyeyishi': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'yjy_xiyizhiyeyishi',
	'USER': 'root',
	'PASSWORD':'123456',
	'HOST':'localhost',
	'PORT':'3306',
    },
    'tcmsq': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'tcmsq',
	'USER': 'root',
	'PASSWORD':'123456',
	'HOST':'localhost',
	'PORT':'3306',
    },
    'yjy_xiyizonghe': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'yjy_xiyizonghe',
	'USER': 'root',
	'PASSWORD':'123456',
	'HOST':'localhost',
	'PORT':'3306',
    },
    'zhongyizonghe': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'yjy_zhongyizonghe',
	'USER': 'root',
	'PASSWORD':'123456',
	'HOST':'localhost',
	'PORT':'3306',
    },
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

USE_I18N = True

USE_L10N = True
AUTH_USER_MODEL = 'auth.User'
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_ROOT = '/www/web/django_video/video_omsa/static/'
STATIC_URL = '/static/'
STAICFILES_DIRS= ( 
         os.path.join(BASE_DIR + '/common_static/'),
)
#############
# debug配置 # 
#############
INTERNAL_IPS=('127.0.0.1',)
## 日志
LOGGING = {  
    'disable_existing_loggers': False,  
    'version': 1,  
    'handlers': {  
        'console': {  
            # logging handler that outputs log messages to terminal  
            'class': 'logging.StreamHandler',  
            'level': 'DEBUG', # message level to be written to console  
        },  
    },  
    'loggers': {  
        '': {  
            # this sets root level logger to log debug and higher level  
            # logs to console. All other loggers inherit settings from  
            # root level logger.  
            'handlers': ['console'],  
            'level': 'DEBUG',  
            'propagate': False, # this tells logger to send logging message  
                                # to its parent (will send if set to True)  
        },  
        'django.db': {  
            # django also has database level logging  
        },  
    },  
}

# django_simple_captcha 验证码配置   
# 格式  
CAPTCHA_OUTPUT_FORMAT = u'%(text_field)s %(hidden_field)s %(image)s'  
# 噪点样式  
CAPTCHA_NOISE_FUNCTIONS = ('captcha.helpers.noise_null', # 没有样式  
    # 'captcha.helpers.noise_arcs', # 线  
    # 'captcha.helpers.noise_dots', # 点  
)  
# 图片大小  
CAPTCHA_IMAGE_SIZE = (200, 25)
CAPTCHA_BACKGROUND_COLOR = '#ffffff'  
CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.random_char_challenge' # 图片中的文字为随机英文字母，如 mdsh  
# CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.math_challenge'    # 图片中的文字为数字表达式，如1+2=</span>  
  
CAPTCHA_LENGTH = 5 # 字符个数
CAPTCHA_TIMEOUT = 1 # 超时(minutes)  
