# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-27 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=b'\xe5\xaf\xbc\xe8\x88\xaa\xe6\xa0\x8f', max_length=40, null=True)),
                ('nnav', models.CharField(blank=True, default=b'\xe4\xba\x8c\xe7\xba\xa7\xe5\x88\x86\xe7\xb1\xbb', max_length=40, null=True)),
                ('nnav_url', models.CharField(blank=True, default=b'#', max_length=40, null=True)),
                ('nnav1', models.CharField(blank=True, default=b'\xe4\xba\x8c\xe7\xba\xa7\xe5\x88\x86\xe7\xb1\xbb1', max_length=40, null=True)),
                ('nnav_url1', models.CharField(blank=True, default=b'#', max_length=40, null=True)),
                ('nnav2', models.CharField(blank=True, default=b'\xe4\xba\x8c\xe7\xba\xa7\xe5\x88\x86\xe7\xb1\xbb2', max_length=40, null=True)),
                ('nnav_url2', models.CharField(blank=True, default=b'#', max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('app_type', models.CharField(default=b'app\xe7\xb1\xbb\xe5\x9e\x8b', max_length=40)),
                ('project_name', models.CharField(default=b'\xe9\xa1\xb9\xe7\x9b\xae\xe7\xb1\xbb\xe5\x9e\x8b', max_length=40)),
                ('marjor_name', models.CharField(default=b'\xe7\xa7\x91\xe7\x9b\xae\xe7\xb1\xbb\xe5\x9e\x8b', max_length=40)),
                ('marjor_teacher', models.CharField(default=b'\xe6\x8e\x88\xe8\xaf\xbe\xe8\x80\x81\xe5\xb8\x88', max_length=40)),
                ('is_shooting', models.CharField(blank=True, max_length=100, verbose_name=b'\xe6\x8b\x8d\xe6\x91\x84\xe6\x83\x85\xe5\x86\xb5')),
                ('cut_time', models.CharField(blank=True, max_length=100, verbose_name=b'\xe5\x89\xaa\xe6\x8e\xa5\xe6\x83\x85\xe5\x86\xb5')),
                ('to_m3u8_time', models.CharField(blank=True, max_length=100, verbose_name=b'\xe5\x88\x87\xe7\x89\x87\xe6\x83\x85\xe5\x86\xb5')),
                ('is_onsandbox', models.CharField(blank=True, max_length=100, verbose_name=b'\xe4\xb8\x8a\xe6\xb2\x99\xe7\x9b\x92\xe6\x83\x85\xe5\x86\xb5')),
                ('content_test', models.CharField(blank=True, max_length=100, verbose_name=b'\xe5\x86\x85\xe5\xae\xb9\xe6\xb5\x8b\xe8\xaf\x95\xe6\x83\x85\xe5\x86\xb5')),
                ('qa_test', models.CharField(blank=True, max_length=100, verbose_name=b'\xe5\xa3\xb0\xe7\x94\xbb\xe6\xb5\x8b\xe8\xaf\x95\xe6\x83\x85\xe5\x86\xb5')),
                ('is_online', models.CharField(max_length=100, verbose_name=b'\xe5\x90\x8c\xe6\xad\xa5\xe5\x88\xb0\xe7\xba\xbf\xe4\xb8\x8a')),
            ],
        ),
    ]
